# Generated by Django 5.1.6 on 2025-02-28 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('inq_id', models.AutoField(primary_key=True, serialize=False)),
                ('inq_email', models.EmailField(max_length=254)),
                ('inq_title', models.CharField(max_length=200)),
                ('inq_content', models.TextField()),
                ('inq_category', models.CharField(choices=[('신고합니다', 'REPORT_ABUSE'), ('계정 접근 불가', 'ACCCOUNT_ACCESS'), ('버그 신고', 'BUG_REPORT'), ('구매 또는 구독 문제', 'PURCHASE_ISSUE'), ('기타 버그', 'OTHER_BUG'), ('계정 삭제 요청', 'ACCOUNT_DELETION')], default='기타 버그', max_length=20)),
                ('send_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
