# Generated by Django 5.1.6 on 2025-03-04 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('langvo', '0003_alter_inquiry_inq_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='inq_category',
            field=models.CharField(choices=[('REPORT_ABUSE', '신고합니다'), ('ACCCOUNT_ACCESS', '계정 접근 불가'), ('BUG_REPORT', '버그 신고'), ('PURCHASE_ISSUE', '구매 또는 구독 문제'), ('OTHER_BUG', '기타 버그'), ('ACCOUNT_DELETION', '계정 삭제 요청')], max_length=20),
        ),
    ]
